/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentManagment;

import AdminManagment.MainLoginFrame;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AddStudentFrame extends javax.swing.JFrame {

    public static boolean gen = false;

    /**
     * Creates new form AddStaff
     */
    public AddStudentFrame() {
        super("Student Registration Frame");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dobLbl = new javax.swing.JLabel();
        mobileLbl = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        rbtMale = new javax.swing.JRadioButton();
        rbtFemale = new javax.swing.JRadioButton();
        namelbl = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        userNameLb = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        passLb = new javax.swing.JLabel();
        cnPassLb = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        cnPassword = new javax.swing.JPasswordField();
        date = new javax.swing.JComboBox();
        year = new javax.swing.JComboBox();
        month = new javax.swing.JComboBox();
        deptLble = new javax.swing.JLabel();
        semLable = new javax.swing.JLabel();
        sem = new javax.swing.JComboBox();
        backBtn = new javax.swing.JButton();
        dept = new javax.swing.JComboBox();
        pMobileLbl = new javax.swing.JLabel();
        parentMobile = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        dobLbl.setText("Date of Birth");

        mobileLbl.setText("Mobile no");

        gender.setText("Gender");

        rbtMale.setBackground(new java.awt.Color(255, 255, 255));
        rbtMale.setText("Male");
        rbtMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMaleActionPerformed(evt);
            }
        });

        rbtFemale.setBackground(new java.awt.Color(255, 255, 255));
        rbtFemale.setText("Female");
        rbtFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFemaleActionPerformed(evt);
            }
        });

        namelbl.setText("Name");

        emailLbl.setText("Email");

        registerBtn.setBackground(new java.awt.Color(51, 204, 0));
        registerBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(255, 0, 0));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        userNameLb.setText("UserName");

        passLb.setText("Password");

        cnPassLb.setText("Confirm password ");

        date.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "1995", "1996", "1997", "1998", "1999", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));

        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "Jan", "Feb", "March", "April", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        deptLble.setText("Depatment");

        semLable.setText("Select Semester");

        sem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semester", "I", "II", "III", "IV", "V", "VI" }));
        sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(51, 51, 255));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        dept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Department", "IT", "COM" }));

        pMobileLbl.setText("Parent mobile no");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pMobileLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gender)
                            .addComponent(dobLbl))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(rbtMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtFemale)
                                .addGap(31, 31, 31)))
                        .addGap(209, 209, 209))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(semLable)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namelbl)
                                    .addComponent(emailLbl)
                                    .addComponent(userNameLb)
                                    .addComponent(passLb)
                                    .addComponent(cnPassLb)
                                    .addComponent(mobileLbl)
                                    .addComponent(deptLble))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mobile, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cnPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(parentMobile))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelbl)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dobLbl))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender)
                    .addComponent(rbtMale)
                    .addComponent(rbtFemale))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deptLble)
                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semLable)
                    .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLbl))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileLbl))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pMobileLbl)
                    .addComponent(parentMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLb)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLb)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnPassLb)
                    .addComponent(cnPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(500, 130, 430, 610);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(140, 20, 410, 410);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 255));
        jLabel12.setText("Register Student");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(510, 20, 420, 100);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(990, 290, 590, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        name.setText(null);
        mobile.setText(null);
        email.setText(null);
        userName.setText(null);
        dept.setSelectedItem("Department");
        date.setSelectedItem("Date");
        month.setSelectedItem("Month");
        year.setSelectedItem("Year");
        sem.setSelectedItem("Semester");
        rbtMale.setSelected(false);
        rbtFemale.setSelected(false);
        password.setText(null);
        cnPassword.setText(null);

    }//GEN-LAST:event_clearBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        String d = (String) date.getSelectedItem();
        String m = (String) month.getSelectedItem();
        String y = (String) year.getSelectedItem();
        String dob = d + " / " + m + " / " + y;

        String str_name = name.getText();
        String str_dept = (String) dept.getSelectedItem();
        String str_mob = mobile.getText();
        String str_parent = parentMobile.getText();
        String str_mail = email.getText();
        String str_sem = (String) sem.getSelectedItem();
        String gn = "";

        if (rbtMale.isSelected()) {
            gn = rbtMale.getText();
        } else if (rbtFemale.isSelected()) {
            gn = rbtFemale.getText();
        }
        String user = userName.getText();
        char ch[] = password.getPassword();
        String pass = String.valueOf(ch);
        char ch1[] = cnPassword.getPassword();
        String cpass = String.valueOf(ch1);

        if ((str_name.isEmpty())) {
            JOptionPane.showMessageDialog(null, "Please enter name");
        } else if (!dOB(d, m, y)) {
            JOptionPane.showMessageDialog(null, "Please Enter Date of Birth");
        } else if (!getGen(gen)) {
            JOptionPane.showMessageDialog(null, "Please Select gender");
        } else if (dept.equals("Department")) {
            JOptionPane.showMessageDialog(null, "Please Select Depatment");
        } else if (!isSelectedsem(str_sem)) {
            JOptionPane.showMessageDialog(null, "Please Select Semester");
        } else if (!getMail(str_mail)) {
            JOptionPane.showMessageDialog(null, "Please enter Valid Email Address");
        } else if (!getmob(str_mob)) {
            JOptionPane.showMessageDialog(null, "Please enter Valid Moblie number ");
        } else if (!getmob(str_parent)) {
            JOptionPane.showMessageDialog(null, "Please enter Valid Moblie Parent Mobile number ");
        } else if (user.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter UserName");
        } else if (!chkpass(pass, cpass)) {
            JOptionPane.showMessageDialog(null, "Please enter Valid Password");
        } else {
            AddStudentClass as = new AddStudentClass();
            boolean flag = as.insertData(str_name, dob, gn, str_dept, str_sem, str_mail, str_mob, user, str_parent, pass);
            if (flag) {
                JOptionPane.showMessageDialog(null, "Registration Successfull");
                this.dispose();
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                MainLoginFrame loginFrame = new MainLoginFrame();
                loginFrame.setVisible(true);
                loginFrame.setSize(dim);
            } else {
                JOptionPane.showMessageDialog(null, "Error occured Please try Again");
            }
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void rbtFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFemaleActionPerformed
        // TODO add your handling code here:
        rbtMale.setSelected(false);
        rbtFemale.setSelected(true);
        gen = true;
    }//GEN-LAST:event_rbtFemaleActionPerformed

    private void rbtMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMaleActionPerformed
        // TODO add your handling code here:
        rbtMale.setSelected(true);
        rbtFemale.setSelected(false);
        gen = true;
    }//GEN-LAST:event_rbtMaleActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_dateActionPerformed

    private void semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        MainLoginFrame loginFrame = new MainLoginFrame();
        loginFrame.setVisible(true);
        loginFrame.setSize(dim);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudentFrame().setVisible(true);
            }
        });
    }

    public static boolean chkpass(String pass, String cpass) {
        boolean flag = false;

        if (!pass.isEmpty() && !cpass.isEmpty()) {
            if (pass.equals(cpass)) {
                flag = true;
            }
        }
        return flag;
    }
    //Email validation check

    public static boolean getMail(String mail) {
        boolean flag = false;

        if (!mail.isEmpty()) {
            if (mail.contains(".") && mail.contains("@")) {
                flag = true;
            }
        }
        return flag;
    }

    //gender validation
    public static boolean getGen(boolean flag) {
        boolean t = false;
        if (flag) {
            t = true;
        }
        return flag;
    }

    public static boolean dOB(String d, String m, String y) {
        boolean flag = false;

        if (!d.equals("Date") && !m.equals("Month") && !y.equals("Year")) {
            flag = true;
        }
        return flag;
    }

    public static boolean isSelectedsem(String sem) {
        boolean flag = false;

        if (!sem.equals("Semester")) {
            flag = true;
        }
        return flag;
    }

    //Mobile number validation check
    public static boolean getmob(String mob) {
        boolean flag = false;
        try {
            if (!mob.isEmpty()) {
                if (mob.length() == 10) {
                    long n = Long.parseLong(mob);
                    flag = true;
                }
            }
        } catch (Exception e) {
        }
        return flag;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel cnPassLb;
    private javax.swing.JPasswordField cnPassword;
    private javax.swing.JComboBox date;
    private javax.swing.JComboBox dept;
    private javax.swing.JLabel deptLble;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mobile;
    private javax.swing.JLabel mobileLbl;
    private javax.swing.JComboBox month;
    private javax.swing.JTextField name;
    private javax.swing.JLabel namelbl;
    private javax.swing.JLabel pMobileLbl;
    private javax.swing.JTextField parentMobile;
    private javax.swing.JLabel passLb;
    private javax.swing.JPasswordField password;
    private javax.swing.JRadioButton rbtFemale;
    private javax.swing.JRadioButton rbtMale;
    private javax.swing.JButton registerBtn;
    private javax.swing.JComboBox sem;
    private javax.swing.JLabel semLable;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel userNameLb;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}