/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package AdminManagment;

import StudentManagment.AddStudentFrame;
import StudentManagment.StudentLoginChecker;
import StudentManagment.UpdateStudentFrame;
import StudentManagment.studentOprationFrame;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import staffMangment.StaffEditFrame;
import staffMangment.StaffLoginChecker;
import staffMangment.StaffOprationFrame;

/**
 *
 * @author HP
 */
public class MainLoginFrame extends javax.swing.JFrame {

    public static String logedUser ;
    
    /**
     * Creates new form AdminLoginFrame
     */
    public MainLoginFrame() {
        super("Login Frame");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        usernameLbl = new javax.swing.JLabel();
        passlbl = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        selectionLbl = new javax.swing.JLabel();
        loginBy = new javax.swing.JComboBox();
        keyImage = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        sysName = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        loginPanel.setFocusCycleRoot(true);
        loginPanel.setName("loginPanel"); // NOI18N

        usernameLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usernameLbl.setText("UserName");

        passlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passlbl.setText("Password");

        userName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        loginBtn.setBackground(new java.awt.Color(0, 0, 255));
        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginBtnFocusGained(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(255, 0, 0));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        selectionLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selectionLbl.setText("Select Login");

        loginBy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin Login", "Staff Login", "Student Login" }));
        loginBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginByActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(usernameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(selectionLbl))
                .addGap(36, 36, 36)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(clearBtn))
                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(userName)
                    .addComponent(loginBy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(loginBy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selectionLbl)))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        loginBy.getAccessibleContext().setAccessibleName("");

        getContentPane().add(loginPanel);
        loginPanel.setBounds(470, 290, 480, 220);

        keyImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminManagment/key.png"))); // NOI18N
        getContentPane().add(keyImage);
        keyImage.setBounds(980, 200, 530, 520);
        getContentPane().add(img);
        img.setBounds(490, 100, 530, 180);
        getContentPane().add(sysName);
        sysName.setBounds(220, 10, 1110, 80);

        registerBtn.setBackground(new java.awt.Color(0, 0, 255));
        registerBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("Student Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(registerBtn);
        registerBtn.setBounds(1370, 30, 180, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
      
        String user = userName.getText();
        char ch[] = password.getPassword();
        String pass=String.valueOf(ch);
        String log = (String) loginBy.getSelectedItem();
        //System.out.println(pass);
        // "Admin Login", "Staff Login", "Student Login" 

        // checks who login 
        //this is for admin login
        if (log.equals("Admin Login")) {

            AdminLoginChecker logCheck = new AdminLoginChecker();
            boolean flag = logCheck.isLogged(user, pass);
            if (flag)
            {              
                AdminUpdateFrame.uname = user; // static datamember of adminupdate frame
                this.dispose();
                AdminOprationFrame of = new AdminOprationFrame();
                of.setVisible(true);
                Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
                of.setSize(d);
                logedUser = user;
            } else {
                JOptionPane.showMessageDialog(null, "Please check Username Password");
            }
       //this is for staff log in 
        } else if (log.equals("Staff Login")) {
           
            StaffLoginChecker logCheck = new StaffLoginChecker();
            boolean flag = logCheck.isLogged(user, pass);
            if (flag) {
               StaffOprationFrame.user=user;               
                this.dispose();
                StaffOprationFrame of = new StaffOprationFrame();
                of.setVisible(true);
                Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
                of.setSize(d);
                logedUser = user;

            } else {
                JOptionPane.showMessageDialog(null, "Please check Username Password");
            }

        } 
        //this for student login 
        else if (log.equals("Student Login")) 
        {
            StudentLoginChecker logCheck = new StudentLoginChecker();
            boolean flag = logCheck.isLogged(user, pass);
            if (flag) 
            {              
                UpdateStudentFrame.uname = user;
                this.dispose();
                studentOprationFrame of = new studentOprationFrame();
                of.setVisible(true);
                Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
                of.setSize(d);
                logedUser = user;
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Please check Username Password");
            }
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        loginBy.setSelectedItem("Admin Login");
        userName.setText(null);
        password.setText(null);                        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void loginBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginBtnFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnFocusGained

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
                this.dispose();
                AddStudentFrame reg = new AddStudentFrame();
                reg.setVisible(true);
                Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
                reg.setSize(d);
    }//GEN-LAST:event_registerBtnActionPerformed

    private void loginByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginByActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel img;
    private javax.swing.JLabel keyImage;
    private javax.swing.JButton loginBtn;
    private javax.swing.JComboBox loginBy;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel passlbl;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel selectionLbl;
    private javax.swing.JLabel sysName;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables
}
